spring.application.name=pharmacy

#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:pharmacy_db
#
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


spring.datasource.url=jdbc:postgresql://localhost:1234/pharmacy_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false


spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations[0]=classpath:/static/
spring.web.resources.static-locations[1]=file:./uploads/