server.port=8085
server.forward-headers-strategy=framework

=== PostgreSQL ===
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/pharmacy_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:login}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pass}
